version: "3.8"

services:
  swhs:
    build: .
    container_name: solarwaterheatingsystem_app
    tty: true
    stdin_open: true
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: solarwaterheatingsystem_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: solarwaterheatingsystem_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: solarwaterheatingsystem_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
